[project]
name = "check-secure-boot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.124.0",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.44",
    "uvicorn[standard]>=0.38.0",
]
